### ISSUE TITLE
Upload jar to releases

### ISSUE THREAD

**Issue by saily** [societe-generale/sonar-openapi#12]
Hi @certsocietegenerale, great work!

Travis offers support for uploading assets to git tags, there's a good example in the [Travis documentation](https://docs.travis-ci.com/user/deployment/releases/). Just add to your `.travis.yml` following snippet:

```yaml

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "build/libs/sonar-openapi-*.jar"
  skip_cleanup: true
  on:
    tags: true
```

Just create an oauth token to upload `jar` from travis to the [github releases section](https://github.com/societe-generale/sonar-openapi/releases) and make it easier for people to use your great plugin!
